# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbi < Formula
  desc ""
  homepage ""
  version "3.2.0-alpha.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metrumresearchgroup/bbi/releases/download/v3.2.0-alpha.1/bbi_darwin_arm64.tar.gz"
      sha256 "b7f615e8749035a87a7a747c622d4521bfea291964d70d9ce4d27b3113bc9464"

      def install
        bin.install "bbi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/bbi/releases/download/v3.2.0-alpha.1/bbi_darwin_amd64.tar.gz"
      sha256 "3aae6032f7ae9a3e67e8cd7b147ae80e1a0876af951b3428114a31f32556f5b2"

      def install
        bin.install "bbi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metrumresearchgroup/bbi/releases/download/v3.2.0-alpha.1/bbi_linux_arm64.tar.gz"
      sha256 "514d8b52cdbf202a15f233679cb3bd8eacd42543d12e021a7188aebb8fd01988"

      def install
        bin.install "bbi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/bbi/releases/download/v3.2.0-alpha.1/bbi_linux_amd64.tar.gz"
      sha256 "3b95251924c85b8d1561f04c28d1ac659ff39d1b8a619e64d34f88f50d9cdebf"

      def install
        bin.install "bbi"
      end
    end
  end
end
