# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fab < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/fab/releases/download/v0.0.1/fab_0.0.1_darwin_amd64.tar.gz"
      sha256 "2d547057db12dae43f8f3fd0583e33480fc2101f24c6be8a57e774b6875ffbcf"

      def install
        bin.install "fab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/fab/releases/download/v0.0.1/fab_0.0.1_linux_amd64.tar.gz"
      sha256 "d50c9928080e3099add4d88a4087239cf925efd6b488723387dbd37df309fa92"

      def install
        bin.install "fab"
      end
    end
  end
end
