# This file was generated by GoReleaser. DO NOT EDIT.
class Pkgr < Formula
  desc ""
  homepage ""
  version "0.5.0-rc.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/metrumresearchgroup/pkgr/releases/download/v0.5.0-rc.2/pkgr_0.5.0-rc.2_darwin_amd64.tar.gz"
    sha256 "bba0d6e462eaffe5ac7599b35ea887c3cb0770ea5f732fd43d5688ea9df22a23"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/pkgr/releases/download/v0.5.0-rc.2/pkgr_0.5.0-rc.2_linux_amd64.tar.gz"
      sha256 "38eec33acf6e6f11fbb4b521e25f0746d1353d555cb128275d93496dee9571ec"
    end
  end

  def install
    bin.install "pkgr"
  end
end
