# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pkgr < Formula
  desc ""
  homepage ""
  version "3.0.0-rc4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/pkgr/releases/download/v3.0.0-rc4/pkgr_3.0.0-rc4_darwin_amd64.tar.gz"
      sha256 "e48cac92eca784df04a4a508c4bfe8e359eb3c2c09ba730b81bcd48dcb9b8caa"

      def install
        bin.install "pkgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/pkgr/releases/download/v3.0.0-rc4/pkgr_3.0.0-rc4_linux_amd64.tar.gz"
      sha256 "107adcbc626948b3a690bf7487a9fe32a6db1e37aeb9ac032eea41185531bece"

      def install
        bin.install "pkgr"
      end
    end
  end
end
