# This file was generated by GoReleaser. DO NOT EDIT.
class Pxr < Formula
  desc ""
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/metrumresearchgroup/pxr/releases/download/0.0.1/pxr_0.0.1_darwin_amd64.tar.gz"
    sha256 "049fdd3322ba212ae41b1c89ee4a7036d09a05df957bf2e4b32e30abe3ff6f9f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/pxr/releases/download/0.0.1/pxr_0.0.1_linux_amd64.tar.gz"
      sha256 "85e3f2750aa8f076b3ba2368c1e95f5b1b45957bb36da2feb9f1ebf3c1c95778"
    end
  end

  def install
    bin.install "pxr"
  end
end
