# This file was generated by GoReleaser. DO NOT EDIT.
class Sdl < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/metrumresearchgroup/sdl/releases/download/v0.1.0/sdl_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "af9985acfbdcb37d491a6a609c1f504760cbbd3eadb8791dcd5a5bd988ec2df8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/sdl/releases/download/v0.1.0/sdl_0.1.0_Linux_x86_64.tar.gz"
      sha256 "79fb3084d7b7d8bdd8ec2622533fb966fcdf417e76bd5460e931b4401e0de238"
    end
  end

  def install
    bin.install "sdl"
  end
end
