# This file was generated by GoReleaser. DO NOT EDIT.
class Sdl < Formula
  desc ""
  homepage ""
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/metrumresearchgroup/sdl/releases/download/v0.1.2/sdl_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "0abd2132c0a63ec9fc1f37f904e8548ae21b816e616562b61a25f292965040a6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/metrumresearchgroup/sdl/releases/download/v0.1.2/sdl_0.1.2_Linux_x86_64.tar.gz"
      sha256 "9b1f703ef20c8e24303f44b95833b59aab7edab83f0e02de6678e738cacc3463"
    end
  end

  def install
    bin.install "sdl"
  end
end
